version: '3.2'
services:
  postgres:
    restart: 'always'
    image: moneyvaluedb
    ports:
      - '5432:5432'
    environment:
      - "FILLA_DB_USER=mvlocal"
      - "FILLA_DB_PASSWORD=mvlocal@007"
      - "FILLA_DB_DATABASE=moneyvalue"
      - "POSTGRES_PASSWORD=password"
    build: './db'
    networks:
      infranet:
        aliases:
          - 'postgres'
networks:
  infranet: